services:
  ava.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8080:8080" 
      - "8081:8081"  
    depends_on:
      - avadb
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  avadb:
    container_name: avadb
    environment:
      SA_PASSWORD: "Admin1234"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1430:1433"
    volumes:
      - ava_sql_data:/var/opt/mssql
