services:
  avadb:
    container_name: avadb
    environment:
      SA_PASSWORD: "Admin1234"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1430:1433"
    volumes:
      - ava_sql_data:/var/opt/mssql
