name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'Ava.Api/ClientApp/ava.web/package-lock.json'

    - name: Install dependencies
      run: |
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi
      working-directory: Ava.Api/ClientApp/ava.web

    - name: Build Angular app
      run: npm run build --if-present
      working-directory: Ava.Api/ClientApp/ava.web

    - name: Run tests
      run: npm test -- --browsers=ChromeHeadless --watch=false
      working-directory: Ava.Api/ClientApp/ava.web
    
    - name: Zip Artifacts
      run: zip -r release.zip ./ -x "node_modules/*" "dist/*"
      working-directory: Ava.Api/ClientApp/ava.web

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: release-artifacts
        path: Ava.Api/ClientApp/ava.web/release.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Download Build Artifacts
      uses: actions/download-artifact@v3
      with:
        name: release-artifacts

    - name: List directory contents after downloading artifact
      run: ls -al /home/runner/work/ava/ava

    - name: Extract Artifacts
      run: unzip -o /home/runner/work/ava/ava/release.zip
      working-directory: Ava.Api/ClientApp/ava.web

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Publish Angular build
      run: |
        npm install
        npm run build --prod
      working-directory: Ava.Api/ClientApp/ava.web

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'pc-ava-web'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './Ava.Api/ClientApp/ava.web/dist/ava.web'
